export const ADD = 'ADD';
export const SUB = 'SUB';

export const HEALTH = 'HEALTH';
export const HEALTH_STATUS = 'HEALTH_STATUS';

export const SYSTEM_ERROR = 'SYSTEM_ERROR';

// for MetaMask
export const METAMASK_ACCOUNT = 'METAMASK_ACCOUNT';
export const METAMASK_NETWORK = 'METAMASK_NETWORK';

// for SimpleToken contract
export const SIMPLE_TOKEN_NAME = 'SIMPLE_TOKEN_NAME';
export const SIMPLE_TOKEN_NAME_SUCCESS = 'SIMPLE_TOKEN_NAME_SUCCESS';
export const SIMPLE_TOKEN_SYMBOL = 'SIMPLE_TOKEN_SYMBOL';
export const SIMPLE_TOKEN_SYMBOL_SUCCESS = 'SIMPLE_TOKEN_SYMBOL_SUCCESS';
export const SIMPLE_TOKEN_DECIMALS = 'SIMPLE_TOKEN_DECIMALS';
export const SIMPLE_TOKEN_DECIMALS_SUCCESS = 'SIMPLE_TOKEN_DECIMALS_SUCCESS';

// for showing progress/onloading
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

// for showing warning message
export const WARNING_OPEN = 'WARNING_OPEN';
export const WARNING_CLOSE = 'WARNING_CLOSE';

// for LOLYAT contract
export const LOLYAT_NAME = 'LOLYAT_NAME';
export const LOLYAT_NAME_SUCCESS = 'LOLYAT_NAME_SUCCESS';
export const LOLYAT_SYMBOL = 'LOLYAT_SYMBOL';
export const LOLYAT_SYMBOL_SUCCESS = 'LOLYAT_SYMBOL_SUCCESS';
export const LOLYAT_TOKEN_URI = 'LOLYAT_TOKEN_URI';
export const LOLYAT_TOKEN_URI_SUCCESS = 'LOLYA_TOKEN_URI_SUCCESS';
export const LOLYAT_OWNER_OF = 'LOLYAT_OWNER_OF';
export const LOLYAT_OWNER_OF_SUCCESS = 'LOLYAT_OWNER_OF_SUCCESS';
export const LOLYAT_TRANSFER_OWNERSHIP = 'LOLYAT_TRANSFER_OWNERSHIP';
export const LOLYAT_TRANSFER_OWNERSHIP_SUCCESS = 'LOLYAT_TRANSFER_OWNERSHIP_SUCCESS';
export const LOLYAT_GET_OWNED_TOKENS = 'LOLYAT_GET_OWNED_TOKENS';
export const LOLYAT_GET_OWNED_TOKENS_SUCCESS = 'LOLYAT_GET_OWNED_TOKENS_SUCCESS';
